name: example
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  boring_widget:
    path: ../boring_widget
  
  cupertino_icons: "0.1.2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  boring_widget_generator:
    path: ../boring_widget_generator/

flutter:
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
