targets:
  $default:
    builders:
      model_widget_generator|model_widget:
        enabled: true

builders:
  model_widget:
      target: ":model_widget_generator"
      import: "package:model_widget_generator/builder.dart"
      builder_factories: ["modelWidget"]
      build_extensions: {".dart":[".model_widget.g.part"]}
      auto_apply: dependents
      build_to: cache
      applies_builders: ["source_gen|combining_builder"]