name: model_widget_generator
version: 0.0.1
author: Swav Kulinski<swav.kulinski@gmail.com>
repository: 
environment: 
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  build: "1.1.3"
  source_gen: "0.9.4+2"
  model_widget:
    path: ../model_widget/

dev_dependencies:
  test: "1.6.2"
  

  
