name: model_widget_generator
version: 0.0.1
author: Swav Kulinski<swav.kulinski@gmail.com>
repository: 
environment: 
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  build: any
  source_gen: any
  model_widget:
    path: ../model_widget/

dev_dependencies:
  test: any
  

  
